# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 572ec2ad0e7a9a78f5f8f0fc96567790006e40a134300644b031f15866ce8174ac9cb3ed49114d8c210987249c6f453f0f5b2ba0f31a2142a170df668109e684

test:
  secret_key_base: b32c9e35f937ac979bbfe7b76149fa1c2b24864351003a21074e37149145f9877643da7ea51649f8b6875e6f2131f0d0753e3a0ecaf0165a6dd42fa8c710d5fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
